sudo: false

language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
  allow_failures:
    - env: DEPENDENCIES=low
    - php: 7.2
  fast_finish: true

env:
    matrix:
        - DEPENDENCIES="high"
        - DEPENDENCIES="low"

before_install:
    - composer self-update
    - composer clear-cache

install:
    - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable; fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable --prefer-lowest; fi

script:
    - make test

notifications:
    email: false

git:
    depth: 1
