# Project information
site_name: GImage
site_description: 'GImage - A PHP library for easy image handling.'
site_author: 'Jose Quintana'
site_url: https://joseluisq.github.io/gimage/
dev_addr: 0.0.0.0:8000

# Repository
repo_name: joseluisq/gimage
repo_url: https://github.com/joseluisq/gimage/
edit_uri: edit/master/docs/content/

docs_dir: 'content'
site_dir: '/tmp/docs'
extra_css:
  - 'assets/style.css'

# Copyright
copyright: Copyright &copy; 2015-2022 Jose Quintana

# Theme
theme:
  name: 'material'
  language: en
  include_sidebar: true
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    # - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: 'Open Sans'
    code: 'Droid Sans Mono'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/joseluisq'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/joseluis_q'

markdown_extensions:
  - admonition
  - abbr
  - def_list
  - md_in_html
  - codehilite
  - admonition
  - meta
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - markdown.extensions.tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      provider: "github"
      user: "facelessuser"
      repo: "pymdown-extensions"
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Content Navigation
nav:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Classes':
    - 'Image': 'classes/image.md'
    - 'Figure': 'classes/figure.md'
    - 'Text': 'classes/text.md'
    - 'Canvas': 'classes/canvas.md'
  - 'Examples':
    - 'Cropping': 'examples/cropping.md'
    - 'Swapping formats': 'examples/swapping-formats.md'
    - 'Resizing': 'examples/resizing.md'
    - 'Rotation': 'examples/rotation.md'
    - 'Creating figures': 'examples/creating-figures.md'
    - 'Text embedding': 'examples/text-embedding.md'
    - 'Composing with canvas': 'examples/composing-with-canvas.md'
    - 'Render images in-memory': 'examples/render-images-in-memory.md'
    - 'Image resource loading': 'examples/image-resource-loading.md'
    - 'Creating a presentation card': 'examples/creating-a-presentation-card.md'
  - 'API Documentation': 'api.md'
  - 'Build documentation': 'build-documentation.md'
